/********************************************************************************
* 文件名称：ActionInfoInit.c
* 作    者：  
* 版    本：V1.0
* 日    期：2022.02.21
* 功能描述: 默认的配置文件。

* 修改说明：   
*
*       >>>>  在工程中的位置  <<<<
*           √  3-应用层
*           	2-协议层
*             1-硬件驱动层
*********************************************************************************
* @copy
* <h2><center>&copy; COPYRIGHT 天津华宁电子有限公司 研发中心 软件部</center></h2>
*********************************************************************************/

#include "includes.h"

#if 0		//默认
ACTION_INFO ActionInformation = 
{
	.Head = 
	{
		.Veron ={0x12,0x34,0x55,0x78},
		.ApplyScene = 1,
		.TotalAction = 16,
		.Verify = 0x3cda,
		.Nouse = {0},
	},
	.Body = 
	{
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x01,
			.ActionName = "移架",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 4,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 3,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x02,
			.ActionName = "升柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 1,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 4,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x03,
			.ActionName = "推溜",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 3,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 1,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x04,
			.ActionName = "降柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 2,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 2,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x05,
			.ActionName = "收平衡",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 6,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 6,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 6,
			.ActionName = "伸平衡",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 5,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 5,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x07,
			.ActionName = "收侧护",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 18,
			.ForbidActionType = 1,
			.ForbidActionID = 8,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 0x08,
			.ActionName = "伸侧护",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 17,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 7,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 10,
			.ActionName = "抬底",
			.MannulCtrlMode = 0x01,
			.AutoCtrlMode = 0,
			.ActionKey = 11,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 9,
			.ActionName = "喷雾",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 12,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = COMBINATION_ACTION,
			.ActionID = 1,
			.ActionName = "自动移架",
			.MannulCtrlMode = DISABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 4,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = GROUP_ACTION,
			.ActionID = 2,
			.ActionName = "成组移架",
			.MannulCtrlMode = DISABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 4,
			.ForbidActionType = GROUP_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = GROUP_ACTION,
			.ActionID = 1,
			.ActionName = "成组推溜",
			.MannulCtrlMode = DISABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 3,
			.ForbidActionType = GROUP_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = GROUP_ACTION,
			.ActionID = 3,
			.ActionName = "成组拉溜",
			.MannulCtrlMode = DISABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 16,
			.ForbidActionType = GROUP_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = GROUP_ACTION,
			.ActionID = 4,
			.ActionName = "成组喷雾",
			.MannulCtrlMode = DISABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 12,
			.ForbidActionType = GROUP_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = GROUP_ACTION,
			.ActionID = 5,
			.ActionName = "成组补压",
			.MannulCtrlMode = DISABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 1,
			.ForbidActionType = GROUP_ACTION,
			.ForbidActionID = 0,
		},
	},
};

#endif

#if 1	//档杆1

ACTION_INFO ActionInformation = 
{
	.Head = 
	{
		.Veron ={0x12,0x34,0x55,0x78},
		.ApplyScene = 1,
		.TotalAction = 28,
		.Verify = 0x3cda,
		.Nouse = {0},
	},
	.Body = 
	{
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 1,
			.ActionName = "降前前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 25,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 2,
			.ActionName = "升前前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 37,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 3,
			.ActionName = "降前后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 26,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 4,
			.ActionName = "升前后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 38,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 5,
			.ActionName = "降中前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 1,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 6,
			.ActionName = "升中前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 13,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 7,
			.ActionName = "降中后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 2,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 8,
			.ActionName = "升中后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 14,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 9,
			.ActionName = "降后前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 3,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 10,
			.ActionName = "升后前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 15,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 11,
			.ActionName = "降后后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 4,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 12,
			.ActionName = "升后后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 16,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 33,
			.ActionName = "前梁伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 5,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 43,
			.ActionName = "侧护伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 17,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 34,
			.ActionName = "前梁收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 6,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 44,
			.ActionName = "侧护收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 18,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 19,
			.ActionName = "前顶伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 7,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 20,
			.ActionName = "前顶收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 19,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 25,
			.ActionName = "前底伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 8,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 26,
			.ActionName = "前底收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 20,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 21,
			.ActionName = "中顶伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 9,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 22,
			.ActionName = "中顶收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 21,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 27,
			.ActionName = "中底伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 10,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 28,
			.ActionName = "中底收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 22,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 23,
			.ActionName = "后顶伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 11,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 24,
			.ActionName = "后顶收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 23,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 29,
			.ActionName = "后底伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 12,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 30,
			.ActionName = "后底收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 24,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
	},
};


#endif

#if 0	//档杆2

ACTION_INFO ActionInformation = 
{
	.Head = 
	{
		.Veron ={0x12,0x34,0x55,0x78},
		.ApplyScene = 1,
		.TotalAction = 30,
		.Verify = 0x3cda,
		.Nouse = {0},
	},
	.Body = 
	{
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 1,
			.ActionName = "降前前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 25,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 2,
			.ActionName = "升前前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 37,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 3,
			.ActionName = "降前后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = ENABLE,
			.ActionKey = 26,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 4,
			.ActionName = "升前后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 38,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 5,
			.ActionName = "降中前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 1,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 6,
			.ActionName = "升中前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 13,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 7,
			.ActionName = "降中后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 2,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 8,
			.ActionName = "升中后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 14,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 9,
			.ActionName = "降后前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 3,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 10,
			.ActionName = "升后前柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 15,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 11,
			.ActionName = "降后后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 4,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 12,
			.ActionName = "升后后柱",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 16,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 13,
			.ActionName = "前推",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 5,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 33,
			.ActionName = "前梁伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 17,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 14,
			.ActionName = "前拉",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 6,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 34,
			.ActionName = "前梁收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 18,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 15,
			.ActionName = "中推",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 7,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 41,
			.ActionName = "底调伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 19,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 16,
			.ActionName = "中拉",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 8,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 42,
			.ActionName = "底调收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 20,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 17,
			.ActionName = "后推",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 9,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 35,
			.ActionName = "前侧帮伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 21,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 18,
			.ActionName = "后拉",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 10,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 36,
			.ActionName = "前侧帮收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 22,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 37,
			.ActionName = "中侧帮伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 11,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 39,
			.ActionName = "后侧帮伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 23,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 38,
			.ActionName = "中侧帮收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 12,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 40,
			.ActionName = "后侧帮收",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 24,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 31,
			.ActionName = "抬底伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 5,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
		{	.ActionType = SIGNAL_ACTION,
			.ActionID = 31,
			.ActionName = "抬底伸",
			.MannulCtrlMode = ENABLE,
			.AutoCtrlMode = DISABLE,
			.ActionKey = 6,
			.ForbidActionType = SIGNAL_ACTION,
			.ForbidActionID = 0,
		},
	},
};


#endif
